$(function () {
  $('.owl-carousel').owlCarousel({
        items:1,
        merge:false,
        loop:true,
        margin:10,
        video:false,
        lazyLoad:true,
        center:true,
        responsive:{
            480:{
                items:1
            },
            600:{
                items:3
            }
        }
    });
});
